name: mito-mia
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - fsspec=2026.2.0
  - s3fs=2026.2.0
  - zarr=3.1.5
  - xarray
  - dask=2026.3.0
  - pytorch>=2.7.1
  - torchvision
  - transformers>=4.56.0
  - scipy
  - scikit-learn
  - pandas
  - matplotlib-base
  - jupyterlab
  - pip:
    - fibsem-tools
